server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native   # 🔥 ВОТ ЭТО НУЖНО

  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:/config/commerce
            - classpath:/config/telemetry

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/