package ru.yandex.practicum.enums;

public enum OrderStatus {
    NEW, ON_PAYMENT, ON_DELIVERY, DONE, ASSEMBLED, PAID, DELIVERED, COMPLETED, DELIVERY_FAILED, ASSEMBLY_FAILED, PAYMENT_FAILED, PRODUCT_RETURNED, CANCELED
}
